//
// Generated by Bluespec Compiler, version 2023.01 (build 52adafa5)
//
// On Sat Sep 28 12:03:07 UTC 2024
//
//
// Ports:
// Name                         I/O  size props
// RDY_request_put                O     1 reg
// response_get                   O   512 reg
// RDY_response_get               O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// request_put                    I   512 reg
// EN_request_put                 I     1
// EN_response_get                I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFFT(CLK,
	     RST_N,

	     request_put,
	     EN_request_put,
	     RDY_request_put,

	     EN_response_get,
	     response_get,
	     RDY_response_get);
  input  CLK;
  input  RST_N;

  // action method request_put
  input  [511 : 0] request_put;
  input  EN_request_put;
  output RDY_request_put;

  // actionvalue method response_get
  input  EN_response_get;
  output [511 : 0] response_get;
  output RDY_response_get;

  // signals for module outputs
  wire [511 : 0] response_get;
  wire RDY_request_put, RDY_response_get;

  // ports of submodule fft_inputFIFO
  wire [511 : 0] fft_inputFIFO$D_IN, fft_inputFIFO$D_OUT;
  wire fft_inputFIFO$CLR,
       fft_inputFIFO$DEQ,
       fft_inputFIFO$EMPTY_N,
       fft_inputFIFO$ENQ,
       fft_inputFIFO$FULL_N;

  // ports of submodule fft_outputFIFO
  wire [511 : 0] fft_outputFIFO$D_IN, fft_outputFIFO$D_OUT;
  wire fft_outputFIFO$CLR,
       fft_outputFIFO$DEQ,
       fft_outputFIFO$EMPTY_N,
       fft_outputFIFO$ENQ,
       fft_outputFIFO$FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_fft_comb_fft,
       CAN_FIRE_request_put,
       CAN_FIRE_response_get,
       WILL_FIRE_RL_fft_comb_fft,
       WILL_FIRE_request_put,
       WILL_FIRE_response_get;

  // remaining internal signals
  wire [63 : 0] IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d411,
		IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d859,
		IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d932,
		IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d252,
		IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d820,
		IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d897,
		_0_CONCAT_IF_fft_inputFIFO_first_BITS_159_TO_12_ETC___d698,
		_0_CONCAT_IF_fft_inputFIFO_first_BITS_159_TO_12_ETC___d90,
		_0_CONCAT_IF_fft_inputFIFO_first_BITS_191_TO_16_ETC___d533,
		_0_CONCAT_IF_fft_inputFIFO_first_BITS_191_TO_16_ETC___d576,
		_0_CONCAT_IF_fft_inputFIFO_first_BITS_287_TO_25_ETC___d1016,
		_0_CONCAT_IF_fft_inputFIFO_first_BITS_287_TO_25_ETC___d656,
		_0_CONCAT_IF_fft_inputFIFO_first_BITS_319_TO_28_ETC___d778,
		_0_CONCAT_IF_fft_inputFIFO_first_BITS_319_TO_28_ETC___d975,
		_0_CONCAT_IF_fft_inputFIFO_first_BITS_415_TO_38_ETC___d212,
		_0_CONCAT_IF_fft_inputFIFO_first_BITS_415_TO_38_ETC___d617,
		_0_CONCAT_IF_fft_inputFIFO_first_BITS_447_TO_41_ETC___d372,
		_0_CONCAT_IF_fft_inputFIFO_first_BITS_447_TO_41_ETC___d739,
		_0_CONCAT_IF_fft_inputFIFO_first_BIT_127_THEN_N_ETC___d10,
		_0_CONCAT_IF_fft_inputFIFO_first_BIT_223_7_THEN_ETC___d51,
		_0_CONCAT_IF_fft_inputFIFO_first_BIT_255_90_THE_ETC___d494,
		_0_CONCAT_IF_fft_inputFIFO_first_BIT_351_88_THE_ETC___d292,
		_0_CONCAT_IF_fft_inputFIFO_first_BIT_383_28_THE_ETC___d132,
		_0_CONCAT_IF_fft_inputFIFO_first_BIT_479_69_THE_ETC___d173,
		_0_CONCAT_IF_fft_inputFIFO_first_BIT_511_29_THE_ETC___d333,
		_0_CONCAT_IF_fft_inputFIFO_first_BIT_95_49_THEN_ETC___d453,
		x__h101008,
		x__h119763,
		x__h125720,
		x__h127055,
		x__h145711,
		x__h154884,
		x__h169264,
		x__h172678,
		x__h185394,
		x__h195276,
		x__h19951,
		x__h210498,
		x__h213900,
		x__h224172,
		x__h23262,
		x__h250747,
		x__h46443,
		x__h49754,
		x__h58573,
		x__h61896,
		x__h65313,
		x__h76283,
		x__h79700,
		x__h85555,
		x__h93716,
		x__h99673;
  wire [47 : 0] IF_fft_inputFIFO_first_BITS_159_TO_128_6_MINUS_ETC___d104,
		IF_fft_inputFIFO_first_BITS_159_TO_128_6_PLUS__ETC___d712,
		IF_fft_inputFIFO_first_BITS_191_TO_160_89_MINU_ETC___d547,
		IF_fft_inputFIFO_first_BITS_191_TO_160_89_PLUS_ETC___d590,
		IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d425,
		IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d873,
		IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d946,
		IF_fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_ETC___d1030,
		IF_fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_ETC___d670,
		IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d266,
		IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d834,
		IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d911,
		IF_fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_ETC___d792,
		IF_fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_ETC___d989,
		IF_fft_inputFIFO_first_BITS_415_TO_384_68_MINU_ETC___d226,
		IF_fft_inputFIFO_first_BITS_415_TO_384_68_PLUS_ETC___d631,
		IF_fft_inputFIFO_first_BITS_447_TO_416_28_MINU_ETC___d386,
		IF_fft_inputFIFO_first_BITS_447_TO_416_28_PLUS_ETC___d753,
		IF_fft_inputFIFO_first_BIT_127_THEN_NEG_0_CONC_ETC___d24,
		IF_fft_inputFIFO_first_BIT_223_7_THEN_NEG_0_CO_ETC___d65,
		IF_fft_inputFIFO_first_BIT_255_90_THEN_NEG_0_C_ETC___d508,
		IF_fft_inputFIFO_first_BIT_351_88_THEN_NEG_0_C_ETC___d306,
		IF_fft_inputFIFO_first_BIT_383_28_THEN_NEG_0_C_ETC___d146,
		IF_fft_inputFIFO_first_BIT_479_69_THEN_NEG_0_C_ETC___d187,
		IF_fft_inputFIFO_first_BIT_511_29_THEN_NEG_0_C_ETC___d347,
		IF_fft_inputFIFO_first_BIT_95_49_THEN_NEG_0_CO_ETC___d467,
		x__h100595,
		x__h119350,
		x__h125307,
		x__h126642,
		x__h145298,
		x__h154471,
		x__h168851,
		x__h172265,
		x__h184981,
		x__h194863,
		x__h19538,
		x__h210085,
		x__h213487,
		x__h223759,
		x__h22849,
		x__h250334,
		x__h46030,
		x__h49341,
		x__h58160,
		x__h61483,
		x__h64900,
		x__h75870,
		x__h79287,
		x__h85142,
		x__h93303,
		x__h99260;
  wire [31 : 0] IF_NOT_IF_NOT_IF_fft_inputFIFO_first_BITS_287__ETC___d445,
		IF_NOT_IF_NOT_IF_fft_inputFIFO_first_BITS_319__ETC___d286,
		fft_inputFIFO_first_BITS_159_TO_128_6_MINUS_IF_ETC___d86,
		fft_inputFIFO_first_BITS_159_TO_128_6_PLUS_IF__ETC___d694,
		fft_inputFIFO_first_BITS_191_TO_160_89_MINUS_I_ETC___d529,
		fft_inputFIFO_first_BITS_191_TO_160_89_PLUS_IF_ETC___d572,
		fft_inputFIFO_first_BITS_287_TO_256_87_MINUS_I_ETC___d407,
		fft_inputFIFO_first_BITS_287_TO_256_87_MINUS_I_ETC___d855,
		fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_IF_ETC___d1012,
		fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_IF_ETC___d652,
		fft_inputFIFO_first_BITS_319_TO_288_27_MINUS_I_ETC___d248,
		fft_inputFIFO_first_BITS_319_TO_288_27_MINUS_I_ETC___d816,
		fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_IF_ETC___d774,
		fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_IF_ETC___d971,
		fft_inputFIFO_first_BITS_415_TO_384_68_MINUS_I_ETC___d208,
		fft_inputFIFO_first_BITS_415_TO_384_68_PLUS_IF_ETC___d613,
		fft_inputFIFO_first_BITS_447_TO_416_28_MINUS_I_ETC___d368,
		fft_inputFIFO_first_BITS_447_TO_416_28_PLUS_IF_ETC___d735,
		x__h100181,
		x__h117184,
		x__h118792,
		x__h118936,
		x__h124893,
		x__h126228,
		x__h1311,
		x__h145744,
		x__h151618,
		x__h160100,
		x__h160112,
		x__h160124,
		x__h165998,
		x__h171851,
		x__h178078,
		x__h178490,
		x__h178623,
		x__h184567,
		x__h185891,
		x__h191916,
		x__h1957,
		x__h19993,
		x__h201243,
		x__h203792,
		x__h203804,
		x__h209671,
		x__h216857,
		x__h217269,
		x__h223345,
		x__h241604,
		x__h241616,
		x__h247481,
		x__h253701,
		x__h253834,
		x__h2603,
		x__h260695,
		x__h267890,
		x__h273922,
		x__h280156,
		x__h287148,
		x__h294341,
		x__h300372,
		x__h30139,
		x__h46485,
		x__h58606,
		x__h58627,
		x__h64486,
		x__h70420,
		x__h72969,
		x__h72981,
		x__h72993,
		x__h73014,
		x__h78873,
		x__h84728,
		x__h85594,
		x__h91916,
		x__h92333,
		x__h92745,
		x__h92889,
		x__h98846;
  wire [15 : 0] y_f__h102169,
		y_f__h107285,
		y_f__h120924,
		y_f__h128216,
		y_f__h133332,
		y_f__h155990,
		y_f__h158619,
		y_f__h170370,
		y_f__h173786,
		y_f__h192981,
		y_f__h202311,
		y_f__h211605,
		y_f__h215005,
		y_f__h231759,
		y_f__h24371,
		y_f__h251853,
		y_f__h27000,
		y_f__h50863,
		y_f__h53492,
		y_f__h63005,
		y_f__h66421,
		y_f__h71488,
		y_f__h77392,
		y_f__h80808,
		y_f__h86662,
		y_f__h94877;

  // action method request_put
  assign RDY_request_put = fft_inputFIFO$FULL_N ;
  assign CAN_FIRE_request_put = fft_inputFIFO$FULL_N ;
  assign WILL_FIRE_request_put = EN_request_put ;

  // actionvalue method response_get
  assign response_get = fft_outputFIFO$D_OUT ;
  assign RDY_response_get = fft_outputFIFO$EMPTY_N ;
  assign CAN_FIRE_response_get = fft_outputFIFO$EMPTY_N ;
  assign WILL_FIRE_response_get = EN_response_get ;

  // submodule fft_inputFIFO
  FIFO2 #(.width(32'd512), .guarded(1'd1)) fft_inputFIFO(.RST(RST_N),
							 .CLK(CLK),
							 .D_IN(fft_inputFIFO$D_IN),
							 .ENQ(fft_inputFIFO$ENQ),
							 .DEQ(fft_inputFIFO$DEQ),
							 .CLR(fft_inputFIFO$CLR),
							 .D_OUT(fft_inputFIFO$D_OUT),
							 .FULL_N(fft_inputFIFO$FULL_N),
							 .EMPTY_N(fft_inputFIFO$EMPTY_N));

  // submodule fft_outputFIFO
  FIFO2 #(.width(32'd512), .guarded(1'd1)) fft_outputFIFO(.RST(RST_N),
							  .CLK(CLK),
							  .D_IN(fft_outputFIFO$D_IN),
							  .ENQ(fft_outputFIFO$ENQ),
							  .DEQ(fft_outputFIFO$DEQ),
							  .CLR(fft_outputFIFO$CLR),
							  .D_OUT(fft_outputFIFO$D_OUT),
							  .FULL_N(fft_outputFIFO$FULL_N),
							  .EMPTY_N(fft_outputFIFO$EMPTY_N));

  // rule RL_fft_comb_fft
  assign CAN_FIRE_RL_fft_comb_fft =
	     fft_inputFIFO$EMPTY_N && fft_outputFIFO$FULL_N ;
  assign WILL_FIRE_RL_fft_comb_fft = CAN_FIRE_RL_fft_comb_fft ;

  // submodule fft_inputFIFO
  assign fft_inputFIFO$D_IN =
	     { request_put[511:448],
	       request_put[255:192],
	       request_put[383:320],
	       request_put[127:64],
	       request_put[447:384],
	       request_put[191:128],
	       request_put[319:256],
	       request_put[63:0] } ;
  assign fft_inputFIFO$ENQ = EN_request_put ;
  assign fft_inputFIFO$DEQ = CAN_FIRE_RL_fft_comb_fft ;
  assign fft_inputFIFO$CLR = 1'b0 ;

  // submodule fft_outputFIFO
  assign fft_outputFIFO$D_IN =
	     { x__h1311,
	       x__h72969,
	       x__h91916,
	       x__h160100,
	       x__h178078,
	       x__h203792,
	       x__h216857,
	       x__h241604,
	       x__h253701,
	       x__h260695,
	       x__h267890,
	       x__h273922,
	       x__h280156,
	       x__h287148,
	       x__h294341,
	       x__h300372 } ;
  assign fft_outputFIFO$ENQ = CAN_FIRE_RL_fft_comb_fft ;
  assign fft_outputFIFO$DEQ = EN_response_get ;
  assign fft_outputFIFO$CLR = 1'b0 ;

  // remaining internal signals
  assign IF_NOT_IF_NOT_IF_fft_inputFIFO_first_BITS_287__ETC___d445 =
	     (!x__h58160[47] &&
	      (x__h58160[31] || x__h58160[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h58160[47] &&
		 (!x__h58160[31] || ~x__h58160[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h58160[31:0]) ;
  assign IF_NOT_IF_NOT_IF_fft_inputFIFO_first_BITS_319__ETC___d286 =
	     (!x__h85142[47] &&
	      (x__h85142[31] || x__h85142[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h85142[47] &&
		 (!x__h85142[31] || ~x__h85142[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h85142[31:0]) ;
  assign IF_fft_inputFIFO_first_BITS_159_TO_128_6_MINUS_ETC___d104 =
	     x__h19951[63:16] + { 32'd0, y_f__h27000 } ;
  assign IF_fft_inputFIFO_first_BITS_159_TO_128_6_PLUS__ETC___d712 =
	     x__h169264[63:16] + { 32'd0, y_f__h170370 } ;
  assign IF_fft_inputFIFO_first_BITS_191_TO_160_89_MINU_ETC___d547 =
	     x__h79700[63:16] + { 32'd0, y_f__h80808 } ;
  assign IF_fft_inputFIFO_first_BITS_191_TO_160_89_PLUS_ETC___d590 =
	     x__h99673[63:16] + { 32'd0, y_f__h107285 } ;
  assign IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d411 =
	     x__h70420 * 32'd46341 ;
  assign IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d425 =
	     x__h58573[63:16] + { 32'd0, y_f__h71488 } ;
  assign IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d859 =
	     x__h201243 * 32'd46341 ;
  assign IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d873 =
	     x__h195276[63:16] + { 32'd0, y_f__h202311 } ;
  assign IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d932 =
	     x__h201243 * 32'd46340 ;
  assign IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d946 =
	     x__h213900[63:16] + { 32'd0, y_f__h215005 } ;
  assign IF_fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_ETC___d1030 =
	     x__h250747[63:16] + { 32'd0, y_f__h251853 } ;
  assign IF_fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_ETC___d670 =
	     x__h145711[63:16] + { 32'd0, y_f__h158619 } ;
  assign IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d252 =
	     x__h85594 * 32'd46341 ;
  assign IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d266 =
	     x__h85555[63:16] + { 32'd0, y_f__h86662 } ;
  assign IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d820 =
	     x__h191916 * 32'd46340 ;
  assign IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d834 =
	     x__h185394[63:16] + { 32'd0, y_f__h192981 } ;
  assign IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d897 =
	     x__h191916 * 32'd46341 ;
  assign IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d911 =
	     x__h210498[63:16] + { 32'd0, y_f__h211605 } ;
  assign IF_fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_ETC___d792 =
	     x__h172678[63:16] + { 32'd0, y_f__h173786 } ;
  assign IF_fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_ETC___d989 =
	     x__h224172[63:16] + { 32'd0, y_f__h231759 } ;
  assign IF_fft_inputFIFO_first_BITS_415_TO_384_68_MINU_ETC___d226 =
	     x__h46443[63:16] + { 32'd0, y_f__h53492 } ;
  assign IF_fft_inputFIFO_first_BITS_415_TO_384_68_PLUS_ETC___d631 =
	     x__h154884[63:16] + { 32'd0, y_f__h155990 } ;
  assign IF_fft_inputFIFO_first_BITS_447_TO_416_28_MINU_ETC___d386 =
	     x__h65313[63:16] + { 32'd0, y_f__h66421 } ;
  assign IF_fft_inputFIFO_first_BITS_447_TO_416_28_PLUS_ETC___d753 =
	     x__h125720[63:16] + { 32'd0, y_f__h133332 } ;
  assign IF_fft_inputFIFO_first_BIT_127_THEN_NEG_0_CONC_ETC___d24 =
	     x__h93716[63:16] + { 32'd0, y_f__h94877 } ;
  assign IF_fft_inputFIFO_first_BIT_223_7_THEN_NEG_0_CO_ETC___d65 =
	     x__h23262[63:16] + { 32'd0, y_f__h24371 } ;
  assign IF_fft_inputFIFO_first_BIT_255_90_THEN_NEG_0_C_ETC___d508 =
	     x__h101008[63:16] + { 32'd0, y_f__h102169 } ;
  assign IF_fft_inputFIFO_first_BIT_351_88_THEN_NEG_0_C_ETC___d306 =
	     x__h61896[63:16] + { 32'd0, y_f__h63005 } ;
  assign IF_fft_inputFIFO_first_BIT_383_28_THEN_NEG_0_C_ETC___d146 =
	     x__h119763[63:16] + { 32'd0, y_f__h120924 } ;
  assign IF_fft_inputFIFO_first_BIT_479_69_THEN_NEG_0_C_ETC___d187 =
	     x__h49754[63:16] + { 32'd0, y_f__h50863 } ;
  assign IF_fft_inputFIFO_first_BIT_511_29_THEN_NEG_0_C_ETC___d347 =
	     x__h127055[63:16] + { 32'd0, y_f__h128216 } ;
  assign IF_fft_inputFIFO_first_BIT_95_49_THEN_NEG_0_CO_ETC___d467 =
	     x__h76283[63:16] + { 32'd0, y_f__h77392 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BITS_159_TO_12_ETC___d698 =
	     { 16'd0,
	       fft_inputFIFO_first_BITS_159_TO_128_6_PLUS_IF__ETC___d694[31] ?
		 -fft_inputFIFO_first_BITS_159_TO_128_6_PLUS_IF__ETC___d694 :
		 fft_inputFIFO_first_BITS_159_TO_128_6_PLUS_IF__ETC___d694,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BITS_159_TO_12_ETC___d90 =
	     { 16'd0,
	       fft_inputFIFO_first_BITS_159_TO_128_6_MINUS_IF_ETC___d86[31] ?
		 -fft_inputFIFO_first_BITS_159_TO_128_6_MINUS_IF_ETC___d86 :
		 fft_inputFIFO_first_BITS_159_TO_128_6_MINUS_IF_ETC___d86,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BITS_191_TO_16_ETC___d533 =
	     { 16'd0,
	       fft_inputFIFO_first_BITS_191_TO_160_89_MINUS_I_ETC___d529[31] ?
		 -fft_inputFIFO_first_BITS_191_TO_160_89_MINUS_I_ETC___d529 :
		 fft_inputFIFO_first_BITS_191_TO_160_89_MINUS_I_ETC___d529,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BITS_191_TO_16_ETC___d576 =
	     { 16'd0,
	       fft_inputFIFO_first_BITS_191_TO_160_89_PLUS_IF_ETC___d572[31] ?
		 -fft_inputFIFO_first_BITS_191_TO_160_89_PLUS_IF_ETC___d572 :
		 fft_inputFIFO_first_BITS_191_TO_160_89_PLUS_IF_ETC___d572,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BITS_287_TO_25_ETC___d1016 =
	     { 16'd0,
	       fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_IF_ETC___d1012[31] ?
		 -fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_IF_ETC___d1012 :
		 fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_IF_ETC___d1012,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BITS_287_TO_25_ETC___d656 =
	     { 16'd0,
	       fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_IF_ETC___d652[31] ?
		 -fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_IF_ETC___d652 :
		 fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_IF_ETC___d652,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BITS_319_TO_28_ETC___d778 =
	     { 16'd0,
	       fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_IF_ETC___d774[31] ?
		 -fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_IF_ETC___d774 :
		 fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_IF_ETC___d774,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BITS_319_TO_28_ETC___d975 =
	     { 16'd0,
	       fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_IF_ETC___d971[31] ?
		 -fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_IF_ETC___d971 :
		 fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_IF_ETC___d971,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BITS_415_TO_38_ETC___d212 =
	     { 16'd0,
	       fft_inputFIFO_first_BITS_415_TO_384_68_MINUS_I_ETC___d208[31] ?
		 -fft_inputFIFO_first_BITS_415_TO_384_68_MINUS_I_ETC___d208 :
		 fft_inputFIFO_first_BITS_415_TO_384_68_MINUS_I_ETC___d208,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BITS_415_TO_38_ETC___d617 =
	     { 16'd0,
	       fft_inputFIFO_first_BITS_415_TO_384_68_PLUS_IF_ETC___d613[31] ?
		 -fft_inputFIFO_first_BITS_415_TO_384_68_PLUS_IF_ETC___d613 :
		 fft_inputFIFO_first_BITS_415_TO_384_68_PLUS_IF_ETC___d613,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BITS_447_TO_41_ETC___d372 =
	     { 16'd0,
	       fft_inputFIFO_first_BITS_447_TO_416_28_MINUS_I_ETC___d368[31] ?
		 -fft_inputFIFO_first_BITS_447_TO_416_28_MINUS_I_ETC___d368 :
		 fft_inputFIFO_first_BITS_447_TO_416_28_MINUS_I_ETC___d368,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BITS_447_TO_41_ETC___d739 =
	     { 16'd0,
	       fft_inputFIFO_first_BITS_447_TO_416_28_PLUS_IF_ETC___d735[31] ?
		 -fft_inputFIFO_first_BITS_447_TO_416_28_PLUS_IF_ETC___d735 :
		 fft_inputFIFO_first_BITS_447_TO_416_28_PLUS_IF_ETC___d735,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BIT_127_THEN_N_ETC___d10 =
	     { 16'd0,
	       fft_inputFIFO$D_OUT[127] ?
		 -fft_inputFIFO$D_OUT[127:96] :
		 fft_inputFIFO$D_OUT[127:96],
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BIT_223_7_THEN_ETC___d51 =
	     { 16'd0,
	       fft_inputFIFO$D_OUT[223] ?
		 -fft_inputFIFO$D_OUT[223:192] :
		 fft_inputFIFO$D_OUT[223:192],
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BIT_255_90_THE_ETC___d494 =
	     { 16'd0,
	       fft_inputFIFO$D_OUT[255] ?
		 -fft_inputFIFO$D_OUT[255:224] :
		 fft_inputFIFO$D_OUT[255:224],
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BIT_351_88_THE_ETC___d292 =
	     { 16'd0,
	       fft_inputFIFO$D_OUT[351] ?
		 -fft_inputFIFO$D_OUT[351:320] :
		 fft_inputFIFO$D_OUT[351:320],
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BIT_383_28_THE_ETC___d132 =
	     { 16'd0,
	       fft_inputFIFO$D_OUT[383] ?
		 -fft_inputFIFO$D_OUT[383:352] :
		 fft_inputFIFO$D_OUT[383:352],
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BIT_479_69_THE_ETC___d173 =
	     { 16'd0,
	       fft_inputFIFO$D_OUT[479] ?
		 -fft_inputFIFO$D_OUT[479:448] :
		 fft_inputFIFO$D_OUT[479:448],
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BIT_511_29_THE_ETC___d333 =
	     { 16'd0,
	       fft_inputFIFO$D_OUT[511] ?
		 -fft_inputFIFO$D_OUT[511:480] :
		 fft_inputFIFO$D_OUT[511:480],
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_first_BIT_95_49_THEN_ETC___d453 =
	     { 16'd0,
	       fft_inputFIFO$D_OUT[95] ?
		 -fft_inputFIFO$D_OUT[95:64] :
		 fft_inputFIFO$D_OUT[95:64],
	       16'd0 } ;
  assign fft_inputFIFO_first_BITS_159_TO_128_6_MINUS_IF_ETC___d86 =
	     fft_inputFIFO$D_OUT[159:128] - x__h19993 ;
  assign fft_inputFIFO_first_BITS_159_TO_128_6_PLUS_IF__ETC___d694 =
	     fft_inputFIFO$D_OUT[159:128] + x__h19993 ;
  assign fft_inputFIFO_first_BITS_191_TO_160_89_MINUS_I_ETC___d529 =
	     fft_inputFIFO$D_OUT[191:160] - x__h100181 ;
  assign fft_inputFIFO_first_BITS_191_TO_160_89_PLUS_IF_ETC___d572 =
	     fft_inputFIFO$D_OUT[191:160] + x__h100181 ;
  assign fft_inputFIFO_first_BITS_287_TO_256_87_MINUS_I_ETC___d407 =
	     x__h58606 - x__h64486 ;
  assign fft_inputFIFO_first_BITS_287_TO_256_87_MINUS_I_ETC___d855 =
	     x__h58606 + x__h64486 ;
  assign fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_IF_ETC___d1012 =
	     x__h145744 + x__h151618 ;
  assign fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_IF_ETC___d652 =
	     x__h145744 - x__h151618 ;
  assign fft_inputFIFO_first_BITS_319_TO_288_27_MINUS_I_ETC___d248 =
	     x__h30139 - x__h185891 ;
  assign fft_inputFIFO_first_BITS_319_TO_288_27_MINUS_I_ETC___d816 =
	     x__h30139 + x__h185891 ;
  assign fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_IF_ETC___d774 =
	     x__h118792 - x__h124893 ;
  assign fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_IF_ETC___d971 =
	     x__h118792 + x__h124893 ;
  assign fft_inputFIFO_first_BITS_415_TO_384_68_MINUS_I_ETC___d208 =
	     fft_inputFIFO$D_OUT[415:384] - x__h46485 ;
  assign fft_inputFIFO_first_BITS_415_TO_384_68_PLUS_IF_ETC___d613 =
	     fft_inputFIFO$D_OUT[415:384] + x__h46485 ;
  assign fft_inputFIFO_first_BITS_447_TO_416_28_MINUS_I_ETC___d368 =
	     fft_inputFIFO$D_OUT[447:416] - x__h126228 ;
  assign fft_inputFIFO_first_BITS_447_TO_416_28_PLUS_IF_ETC___d735 =
	     fft_inputFIFO$D_OUT[447:416] + x__h126228 ;
  assign x__h100181 =
	     (!x__h100595[47] &&
	      (x__h100595[31] || x__h100595[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h100595[47] &&
		 (!x__h100595[31] || ~x__h100595[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h100595[31:0]) ;
  assign x__h100595 =
	     (!x__h101008[63] &&
	      IF_fft_inputFIFO_first_BIT_255_90_THEN_NEG_0_C_ETC___d508[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BIT_255_90_THEN_NEG_0_C_ETC___d508 ;
  assign x__h101008 =
	     fft_inputFIFO$D_OUT[255] ?
	       -_0_CONCAT_IF_fft_inputFIFO_first_BIT_255_90_THE_ETC___d494 :
	       _0_CONCAT_IF_fft_inputFIFO_first_BIT_255_90_THE_ETC___d494 ;
  assign x__h117184 =
	     32'd0 -
	     ((!x__h145298[47] &&
	       (x__h145298[31] || x__h145298[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h145298[47] &&
		  (!x__h145298[31] || ~x__h145298[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h145298[31:0])) ;
  assign x__h118792 = fft_inputFIFO$D_OUT[319:288] + x__h118936 ;
  assign x__h118936 =
	     (!x__h119350[47] &&
	      (x__h119350[31] || x__h119350[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h119350[47] &&
		 (!x__h119350[31] || ~x__h119350[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h119350[31:0]) ;
  assign x__h119350 =
	     (!x__h119763[63] &&
	      IF_fft_inputFIFO_first_BIT_383_28_THEN_NEG_0_C_ETC___d146[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BIT_383_28_THEN_NEG_0_C_ETC___d146 ;
  assign x__h119763 =
	     fft_inputFIFO$D_OUT[383] ?
	       -_0_CONCAT_IF_fft_inputFIFO_first_BIT_383_28_THE_ETC___d132 :
	       _0_CONCAT_IF_fft_inputFIFO_first_BIT_383_28_THE_ETC___d132 ;
  assign x__h124893 =
	     (!x__h125307[47] &&
	      (x__h125307[31] || x__h125307[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h125307[47] &&
		 (!x__h125307[31] || ~x__h125307[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h125307[31:0]) ;
  assign x__h125307 =
	     (!x__h125720[63] &&
	      IF_fft_inputFIFO_first_BITS_447_TO_416_28_PLUS_ETC___d753[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_447_TO_416_28_PLUS_ETC___d753 ;
  assign x__h125720 =
	     fft_inputFIFO_first_BITS_447_TO_416_28_PLUS_IF_ETC___d735[31] ?
	       -_0_CONCAT_IF_fft_inputFIFO_first_BITS_447_TO_41_ETC___d739 :
	       _0_CONCAT_IF_fft_inputFIFO_first_BITS_447_TO_41_ETC___d739 ;
  assign x__h126228 =
	     (!x__h126642[47] &&
	      (x__h126642[31] || x__h126642[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h126642[47] &&
		 (!x__h126642[31] || ~x__h126642[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h126642[31:0]) ;
  assign x__h126642 =
	     (!x__h127055[63] &&
	      IF_fft_inputFIFO_first_BIT_511_29_THEN_NEG_0_C_ETC___d347[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BIT_511_29_THEN_NEG_0_C_ETC___d347 ;
  assign x__h127055 =
	     fft_inputFIFO$D_OUT[511] ?
	       -_0_CONCAT_IF_fft_inputFIFO_first_BIT_511_29_THE_ETC___d333 :
	       _0_CONCAT_IF_fft_inputFIFO_first_BIT_511_29_THE_ETC___d333 ;
  assign x__h1311 = x__h1957 - x__h253834 ;
  assign x__h145298 =
	     (!x__h145711[63] &&
	      IF_fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_ETC___d670[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_ETC___d670 ;
  assign x__h145711 =
	     fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_IF_ETC___d652[31] ?
	       _0_CONCAT_IF_fft_inputFIFO_first_BITS_287_TO_25_ETC___d656 :
	       -_0_CONCAT_IF_fft_inputFIFO_first_BITS_287_TO_25_ETC___d656 ;
  assign x__h145744 = fft_inputFIFO$D_OUT[287:256] + x__h58627 ;
  assign x__h151618 =
	     (!x__h154471[47] &&
	      (x__h154471[31] || x__h154471[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h154471[47] &&
		 (!x__h154471[31] || ~x__h154471[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h154471[31:0]) ;
  assign x__h154471 =
	     (!x__h154884[63] &&
	      IF_fft_inputFIFO_first_BITS_415_TO_384_68_PLUS_ETC___d631[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_415_TO_384_68_PLUS_ETC___d631 ;
  assign x__h154884 =
	     fft_inputFIFO_first_BITS_415_TO_384_68_PLUS_IF_ETC___d613[31] ?
	       -_0_CONCAT_IF_fft_inputFIFO_first_BITS_415_TO_38_ETC___d617 :
	       _0_CONCAT_IF_fft_inputFIFO_first_BITS_415_TO_38_ETC___d617 ;
  assign x__h160100 = x__h160112 - x__h171851 ;
  assign x__h160112 = x__h160124 - x__h165998 ;
  assign x__h160124 = fft_inputFIFO$D_OUT[31:0] + x__h73014 ;
  assign x__h165998 =
	     (!x__h168851[47] &&
	      (x__h168851[31] || x__h168851[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h168851[47] &&
		 (!x__h168851[31] || ~x__h168851[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h168851[31:0]) ;
  assign x__h168851 =
	     (!x__h169264[63] &&
	      IF_fft_inputFIFO_first_BITS_159_TO_128_6_PLUS__ETC___d712[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_159_TO_128_6_PLUS__ETC___d712 ;
  assign x__h169264 =
	     fft_inputFIFO_first_BITS_159_TO_128_6_PLUS_IF__ETC___d694[31] ?
	       -_0_CONCAT_IF_fft_inputFIFO_first_BITS_159_TO_12_ETC___d698 :
	       _0_CONCAT_IF_fft_inputFIFO_first_BITS_159_TO_12_ETC___d698 ;
  assign x__h171851 =
	     (!x__h172265[47] &&
	      (x__h172265[31] || x__h172265[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h172265[47] &&
		 (!x__h172265[31] || ~x__h172265[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h172265[31:0]) ;
  assign x__h172265 =
	     (!x__h172678[63] &&
	      IF_fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_ETC___d792[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_ETC___d792 ;
  assign x__h172678 =
	     fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_IF_ETC___d774[31] ?
	       _0_CONCAT_IF_fft_inputFIFO_first_BITS_319_TO_28_ETC___d778 :
	       -_0_CONCAT_IF_fft_inputFIFO_first_BITS_319_TO_28_ETC___d778 ;
  assign x__h178078 = x__h178490 - x__h184567 ;
  assign x__h178490 = x__h2603 + x__h178623 ;
  assign x__h178623 =
	     32'd0 -
	     ((!x__h19538[47] &&
	       (x__h19538[31] || x__h19538[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h19538[47] &&
		  (!x__h19538[31] || ~x__h19538[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h19538[31:0])) ;
  assign x__h184567 =
	     ((!x__h184981[47] &&
	       (x__h184981[31] || x__h184981[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h184981[47] &&
		  (!x__h184981[31] || ~x__h184981[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h184981[31:0])) -
	     ((!x__h194863[47] &&
	       (x__h194863[31] || x__h194863[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h194863[47] &&
		  (!x__h194863[31] || ~x__h194863[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h194863[31:0])) ;
  assign x__h184981 =
	     (!x__h185394[63] &&
	      IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d834[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d834 ;
  assign x__h185394 =
	     fft_inputFIFO_first_BITS_319_TO_288_27_MINUS_I_ETC___d816[31] ?
	       -IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d820 :
	       IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d820 ;
  assign x__h185891 =
	     32'd0 -
	     ((!x__h46030[47] &&
	       (x__h46030[31] || x__h46030[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h46030[47] &&
		  (!x__h46030[31] || ~x__h46030[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h46030[31:0])) ;
  assign x__h191916 =
	     fft_inputFIFO_first_BITS_319_TO_288_27_MINUS_I_ETC___d816[31] ?
	       -fft_inputFIFO_first_BITS_319_TO_288_27_MINUS_I_ETC___d816 :
	       fft_inputFIFO_first_BITS_319_TO_288_27_MINUS_I_ETC___d816 ;
  assign x__h194863 =
	     (!x__h195276[63] &&
	      IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d873[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d873 ;
  assign x__h195276 =
	     fft_inputFIFO_first_BITS_287_TO_256_87_MINUS_I_ETC___d855[31] ?
	       IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d859 :
	       -IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d859 ;
  assign x__h19538 =
	     (!x__h19951[63] &&
	      IF_fft_inputFIFO_first_BITS_159_TO_128_6_MINUS_ETC___d104[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_159_TO_128_6_MINUS_ETC___d104 ;
  assign x__h1957 = x__h2603 - x__h178623 ;
  assign x__h19951 =
	     fft_inputFIFO_first_BITS_159_TO_128_6_MINUS_IF_ETC___d86[31] ?
	       _0_CONCAT_IF_fft_inputFIFO_first_BITS_159_TO_12_ETC___d90 :
	       -_0_CONCAT_IF_fft_inputFIFO_first_BITS_159_TO_12_ETC___d90 ;
  assign x__h19993 =
	     (!x__h22849[47] &&
	      (x__h22849[31] || x__h22849[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h22849[47] &&
		 (!x__h22849[31] || ~x__h22849[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h22849[31:0]) ;
  assign x__h201243 =
	     fft_inputFIFO_first_BITS_287_TO_256_87_MINUS_I_ETC___d855[31] ?
	       -fft_inputFIFO_first_BITS_287_TO_256_87_MINUS_I_ETC___d855 :
	       fft_inputFIFO_first_BITS_287_TO_256_87_MINUS_I_ETC___d855 ;
  assign x__h203792 = x__h203804 - x__h209671 ;
  assign x__h203804 = x__h72993 + x__h78873 ;
  assign x__h209671 =
	     ((!x__h210085[47] &&
	       (x__h210085[31] || x__h210085[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h210085[47] &&
		  (!x__h210085[31] || ~x__h210085[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h210085[31:0])) +
	     ((!x__h213487[47] &&
	       (x__h213487[31] || x__h213487[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h213487[47] &&
		  (!x__h213487[31] || ~x__h213487[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h213487[31:0])) ;
  assign x__h210085 =
	     (!x__h210498[63] &&
	      IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d911[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d911 ;
  assign x__h210498 =
	     fft_inputFIFO_first_BITS_319_TO_288_27_MINUS_I_ETC___d816[31] ?
	       IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d897 :
	       -IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d897 ;
  assign x__h213487 =
	     (!x__h213900[63] &&
	      IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d946[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d946 ;
  assign x__h213900 =
	     fft_inputFIFO_first_BITS_287_TO_256_87_MINUS_I_ETC___d855[31] ?
	       -IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d932 :
	       IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d932 ;
  assign x__h216857 = x__h217269 - x__h223345 ;
  assign x__h217269 = x__h92745 + x__h98846 ;
  assign x__h223345 =
	     (!x__h223759[47] &&
	      (x__h223759[31] || x__h223759[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h223759[47] &&
		 (!x__h223759[31] || ~x__h223759[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h223759[31:0]) ;
  assign x__h223759 =
	     (!x__h224172[63] &&
	      IF_fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_ETC___d989[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_ETC___d989 ;
  assign x__h224172 =
	     fft_inputFIFO_first_BITS_319_TO_288_27_PLUS_IF_ETC___d971[31] ?
	       -_0_CONCAT_IF_fft_inputFIFO_first_BITS_319_TO_28_ETC___d975 :
	       _0_CONCAT_IF_fft_inputFIFO_first_BITS_319_TO_28_ETC___d975 ;
  assign x__h22849 =
	     (!x__h23262[63] &&
	      IF_fft_inputFIFO_first_BIT_223_7_THEN_NEG_0_CO_ETC___d65[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BIT_223_7_THEN_NEG_0_CO_ETC___d65 ;
  assign x__h23262 =
	     fft_inputFIFO$D_OUT[223] ?
	       -_0_CONCAT_IF_fft_inputFIFO_first_BIT_223_7_THEN_ETC___d51 :
	       _0_CONCAT_IF_fft_inputFIFO_first_BIT_223_7_THEN_ETC___d51 ;
  assign x__h241604 = x__h241616 - x__h247481 ;
  assign x__h241616 = x__h160124 + x__h165998 ;
  assign x__h247481 =
	     (!x__h250334[47] &&
	      (x__h250334[31] || x__h250334[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h250334[47] &&
		 (!x__h250334[31] || ~x__h250334[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h250334[31:0]) ;
  assign x__h250334 =
	     (!x__h250747[63] &&
	      IF_fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_ETC___d1030[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_ETC___d1030 ;
  assign x__h250747 =
	     fft_inputFIFO_first_BITS_287_TO_256_87_PLUS_IF_ETC___d1012[31] ?
	       -_0_CONCAT_IF_fft_inputFIFO_first_BITS_287_TO_25_ETC___d1016 :
	       _0_CONCAT_IF_fft_inputFIFO_first_BITS_287_TO_25_ETC___d1016 ;
  assign x__h253701 = x__h1957 + x__h253834 ;
  assign x__h253834 =
	     IF_NOT_IF_NOT_IF_fft_inputFIFO_first_BITS_319__ETC___d286 -
	     IF_NOT_IF_NOT_IF_fft_inputFIFO_first_BITS_287__ETC___d445 ;
  assign x__h2603 = fft_inputFIFO$D_OUT[63:32] - x__h92889 ;
  assign x__h260695 = x__h72981 + x__h84728 ;
  assign x__h267890 = x__h92333 + x__h117184 ;
  assign x__h273922 = x__h160112 + x__h171851 ;
  assign x__h280156 = x__h178490 + x__h184567 ;
  assign x__h287148 = x__h203804 + x__h209671 ;
  assign x__h294341 = x__h217269 + x__h223345 ;
  assign x__h300372 = x__h241616 + x__h247481 ;
  assign x__h30139 = fft_inputFIFO$D_OUT[319:288] - x__h118936 ;
  assign x__h46030 =
	     (!x__h46443[63] &&
	      IF_fft_inputFIFO_first_BITS_415_TO_384_68_MINU_ETC___d226[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_415_TO_384_68_MINU_ETC___d226 ;
  assign x__h46443 =
	     fft_inputFIFO_first_BITS_415_TO_384_68_MINUS_I_ETC___d208[31] ?
	       _0_CONCAT_IF_fft_inputFIFO_first_BITS_415_TO_38_ETC___d212 :
	       -_0_CONCAT_IF_fft_inputFIFO_first_BITS_415_TO_38_ETC___d212 ;
  assign x__h46485 =
	     (!x__h49341[47] &&
	      (x__h49341[31] || x__h49341[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h49341[47] &&
		 (!x__h49341[31] || ~x__h49341[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h49341[31:0]) ;
  assign x__h49341 =
	     (!x__h49754[63] &&
	      IF_fft_inputFIFO_first_BIT_479_69_THEN_NEG_0_C_ETC___d187[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BIT_479_69_THEN_NEG_0_C_ETC___d187 ;
  assign x__h49754 =
	     fft_inputFIFO$D_OUT[479] ?
	       -_0_CONCAT_IF_fft_inputFIFO_first_BIT_479_69_THE_ETC___d173 :
	       _0_CONCAT_IF_fft_inputFIFO_first_BIT_479_69_THE_ETC___d173 ;
  assign x__h58160 =
	     (!x__h58573[63] &&
	      IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d425[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d425 ;
  assign x__h58573 =
	     fft_inputFIFO_first_BITS_287_TO_256_87_MINUS_I_ETC___d407[31] ?
	       IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d411 :
	       -IF_fft_inputFIFO_first_BITS_287_TO_256_87_MINU_ETC___d411 ;
  assign x__h58606 = fft_inputFIFO$D_OUT[287:256] - x__h58627 ;
  assign x__h58627 =
	     (!x__h61483[47] &&
	      (x__h61483[31] || x__h61483[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h61483[47] &&
		 (!x__h61483[31] || ~x__h61483[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h61483[31:0]) ;
  assign x__h61483 =
	     (!x__h61896[63] &&
	      IF_fft_inputFIFO_first_BIT_351_88_THEN_NEG_0_C_ETC___d306[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BIT_351_88_THEN_NEG_0_C_ETC___d306 ;
  assign x__h61896 =
	     fft_inputFIFO$D_OUT[351] ?
	       -_0_CONCAT_IF_fft_inputFIFO_first_BIT_351_88_THE_ETC___d292 :
	       _0_CONCAT_IF_fft_inputFIFO_first_BIT_351_88_THE_ETC___d292 ;
  assign x__h64486 =
	     (!x__h64900[47] &&
	      (x__h64900[31] || x__h64900[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h64900[47] &&
		 (!x__h64900[31] || ~x__h64900[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h64900[31:0]) ;
  assign x__h64900 =
	     (!x__h65313[63] &&
	      IF_fft_inputFIFO_first_BITS_447_TO_416_28_MINU_ETC___d386[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_447_TO_416_28_MINU_ETC___d386 ;
  assign x__h65313 =
	     fft_inputFIFO_first_BITS_447_TO_416_28_MINUS_I_ETC___d368[31] ?
	       _0_CONCAT_IF_fft_inputFIFO_first_BITS_447_TO_41_ETC___d372 :
	       -_0_CONCAT_IF_fft_inputFIFO_first_BITS_447_TO_41_ETC___d372 ;
  assign x__h70420 =
	     fft_inputFIFO_first_BITS_287_TO_256_87_MINUS_I_ETC___d407[31] ?
	       -fft_inputFIFO_first_BITS_287_TO_256_87_MINUS_I_ETC___d407 :
	       fft_inputFIFO_first_BITS_287_TO_256_87_MINUS_I_ETC___d407 ;
  assign x__h72969 = x__h72981 - x__h84728 ;
  assign x__h72981 = x__h72993 - x__h78873 ;
  assign x__h72993 = fft_inputFIFO$D_OUT[31:0] - x__h73014 ;
  assign x__h73014 =
	     (!x__h75870[47] &&
	      (x__h75870[31] || x__h75870[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h75870[47] &&
		 (!x__h75870[31] || ~x__h75870[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h75870[31:0]) ;
  assign x__h75870 =
	     (!x__h76283[63] &&
	      IF_fft_inputFIFO_first_BIT_95_49_THEN_NEG_0_CO_ETC___d467[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BIT_95_49_THEN_NEG_0_CO_ETC___d467 ;
  assign x__h76283 =
	     fft_inputFIFO$D_OUT[95] ?
	       -_0_CONCAT_IF_fft_inputFIFO_first_BIT_95_49_THEN_ETC___d453 :
	       _0_CONCAT_IF_fft_inputFIFO_first_BIT_95_49_THEN_ETC___d453 ;
  assign x__h78873 =
	     (!x__h79287[47] &&
	      (x__h79287[31] || x__h79287[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h79287[47] &&
		 (!x__h79287[31] || ~x__h79287[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h79287[31:0]) ;
  assign x__h79287 =
	     (!x__h79700[63] &&
	      IF_fft_inputFIFO_first_BITS_191_TO_160_89_MINU_ETC___d547[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_191_TO_160_89_MINU_ETC___d547 ;
  assign x__h79700 =
	     fft_inputFIFO_first_BITS_191_TO_160_89_MINUS_I_ETC___d529[31] ?
	       _0_CONCAT_IF_fft_inputFIFO_first_BITS_191_TO_16_ETC___d533 :
	       -_0_CONCAT_IF_fft_inputFIFO_first_BITS_191_TO_16_ETC___d533 ;
  assign x__h84728 =
	     IF_NOT_IF_NOT_IF_fft_inputFIFO_first_BITS_319__ETC___d286 +
	     IF_NOT_IF_NOT_IF_fft_inputFIFO_first_BITS_287__ETC___d445 ;
  assign x__h85142 =
	     (!x__h85555[63] &&
	      IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d266[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d266 ;
  assign x__h85555 =
	     fft_inputFIFO_first_BITS_319_TO_288_27_MINUS_I_ETC___d248[31] ?
	       IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d252 :
	       -IF_fft_inputFIFO_first_BITS_319_TO_288_27_MINU_ETC___d252 ;
  assign x__h85594 =
	     fft_inputFIFO_first_BITS_319_TO_288_27_MINUS_I_ETC___d248[31] ?
	       -fft_inputFIFO_first_BITS_319_TO_288_27_MINUS_I_ETC___d248 :
	       fft_inputFIFO_first_BITS_319_TO_288_27_MINUS_I_ETC___d248 ;
  assign x__h91916 = x__h92333 - x__h117184 ;
  assign x__h92333 = x__h92745 - x__h98846 ;
  assign x__h92745 = fft_inputFIFO$D_OUT[63:32] + x__h92889 ;
  assign x__h92889 =
	     (!x__h93303[47] &&
	      (x__h93303[31] || x__h93303[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h93303[47] &&
		 (!x__h93303[31] || ~x__h93303[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h93303[31:0]) ;
  assign x__h93303 =
	     (!x__h93716[63] &&
	      IF_fft_inputFIFO_first_BIT_127_THEN_NEG_0_CONC_ETC___d24[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BIT_127_THEN_NEG_0_CONC_ETC___d24 ;
  assign x__h93716 =
	     fft_inputFIFO$D_OUT[127] ?
	       -_0_CONCAT_IF_fft_inputFIFO_first_BIT_127_THEN_N_ETC___d10 :
	       _0_CONCAT_IF_fft_inputFIFO_first_BIT_127_THEN_N_ETC___d10 ;
  assign x__h98846 =
	     (!x__h99260[47] &&
	      (x__h99260[31] || x__h99260[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h99260[47] &&
		 (!x__h99260[31] || ~x__h99260[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h99260[31:0]) ;
  assign x__h99260 =
	     (!x__h99673[63] &&
	      IF_fft_inputFIFO_first_BITS_191_TO_160_89_PLUS_ETC___d590[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_first_BITS_191_TO_160_89_PLUS_ETC___d590 ;
  assign x__h99673 =
	     fft_inputFIFO_first_BITS_191_TO_160_89_PLUS_IF_ETC___d572[31] ?
	       -_0_CONCAT_IF_fft_inputFIFO_first_BITS_191_TO_16_ETC___d576 :
	       _0_CONCAT_IF_fft_inputFIFO_first_BITS_191_TO_16_ETC___d576 ;
  assign y_f__h102169 =
	     (x__h101008[15] &&
	      (x__h101008[63] || x__h101008[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h107285 =
	     (x__h99673[15] && (x__h99673[63] || x__h99673[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h120924 =
	     (x__h119763[15] &&
	      (x__h119763[63] || x__h119763[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h128216 =
	     (x__h127055[15] &&
	      (x__h127055[63] || x__h127055[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h133332 =
	     (x__h125720[15] &&
	      (x__h125720[63] || x__h125720[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h155990 =
	     (x__h154884[15] &&
	      (x__h154884[63] || x__h154884[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h158619 =
	     (x__h145711[15] &&
	      (x__h145711[63] || x__h145711[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h170370 =
	     (x__h169264[15] &&
	      (x__h169264[63] || x__h169264[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h173786 =
	     (x__h172678[15] &&
	      (x__h172678[63] || x__h172678[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h192981 =
	     (x__h185394[15] &&
	      (x__h185394[63] || x__h185394[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h202311 =
	     (x__h195276[15] &&
	      (x__h195276[63] || x__h195276[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h211605 =
	     (x__h210498[15] &&
	      (x__h210498[63] || x__h210498[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h215005 =
	     (x__h213900[15] &&
	      (x__h213900[63] || x__h213900[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h231759 =
	     (x__h224172[15] &&
	      (x__h224172[63] || x__h224172[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h24371 =
	     (x__h23262[15] && (x__h23262[63] || x__h23262[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h251853 =
	     (x__h250747[15] &&
	      (x__h250747[63] || x__h250747[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h27000 =
	     (x__h19951[15] && (x__h19951[63] || x__h19951[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h50863 =
	     (x__h49754[15] && (x__h49754[63] || x__h49754[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h53492 =
	     (x__h46443[15] && (x__h46443[63] || x__h46443[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h63005 =
	     (x__h61896[15] && (x__h61896[63] || x__h61896[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h66421 =
	     (x__h65313[15] && (x__h65313[63] || x__h65313[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h71488 =
	     (x__h58573[15] && (x__h58573[63] || x__h58573[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h77392 =
	     (x__h76283[15] && (x__h76283[63] || x__h76283[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h80808 =
	     (x__h79700[15] && (x__h79700[63] || x__h79700[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h86662 =
	     (x__h85555[15] && (x__h85555[63] || x__h85555[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h94877 =
	     (x__h93716[15] && (x__h93716[63] || x__h93716[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
endmodule  // mkFFT

