//
// Generated by Bluespec Compiler, version 2023.01 (build 52adafa5)
//
// On Mon Sep 30 06:56:14 UTC 2024
//
//
// Ports:
// Name                         I/O  size props
// RDY_request_put                O     1 reg
// response_get                   O   512 reg
// RDY_response_get               O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// request_put                    I   512 reg
// EN_request_put                 I     1
// EN_response_get                I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFFT(CLK,
	     RST_N,

	     request_put,
	     EN_request_put,
	     RDY_request_put,

	     EN_response_get,
	     response_get,
	     RDY_response_get);
  input  CLK;
  input  RST_N;

  // action method request_put
  input  [511 : 0] request_put;
  input  EN_request_put;
  output RDY_request_put;

  // actionvalue method response_get
  input  EN_response_get;
  output [511 : 0] response_get;
  output RDY_response_get;

  // signals for module outputs
  wire [511 : 0] response_get;
  wire RDY_request_put, RDY_response_get;

  // register fft_counter
  reg [1 : 0] fft_counter;
  wire [1 : 0] fft_counter$D_IN;
  wire fft_counter$EN;

  // register fft_sReg
  reg [511 : 0] fft_sReg;
  wire [511 : 0] fft_sReg$D_IN;
  wire fft_sReg$EN;

  // ports of submodule fft_counter_double_write_error
  wire fft_counter_double_write_error$D_IN,
       fft_counter_double_write_error$EN,
       fft_counter_double_write_error$Q_OUT;

  // ports of submodule fft_inputFIFO
  wire [511 : 0] fft_inputFIFO$D_IN, fft_inputFIFO$D_OUT;
  wire fft_inputFIFO$CLR,
       fft_inputFIFO$DEQ,
       fft_inputFIFO$EMPTY_N,
       fft_inputFIFO$ENQ,
       fft_inputFIFO$FULL_N;

  // ports of submodule fft_outputFIFO
  wire [511 : 0] fft_outputFIFO$D_IN, fft_outputFIFO$D_OUT;
  wire fft_outputFIFO$CLR,
       fft_outputFIFO$DEQ,
       fft_outputFIFO$EMPTY_N,
       fft_outputFIFO$ENQ,
       fft_outputFIFO$FULL_N;

  // ports of submodule fft_sReg_double_write_error
  wire fft_sReg_double_write_error$D_IN,
       fft_sReg_double_write_error$EN,
       fft_sReg_double_write_error$Q_OUT;

  // rule scheduling signals
  wire CAN_FIRE_RL_fft_circ_fft,
       CAN_FIRE_request_put,
       CAN_FIRE_response_get,
       WILL_FIRE_RL_fft_circ_fft,
       WILL_FIRE_request_put,
       WILL_FIRE_response_get;

  // remaining internal signals
  reg [15 : 0] CASE_fft_counter_0_0_1_0_2_46340_3_DONTCARE_DO_ETC__q6,
	       SEL_ARR_0_0_19195_9_fft_counter___d40,
	       SEL_ARR_0_0_65535_78_fft_counter___d479,
	       SEL_ARR_0_65535_65535_3_fft_counter___d84,
	       SEL_ARR_1_0_0_25_fft_counter___d226,
	       SEL_ARR_1_0_65535_5_fft_counter___d26,
	       SEL_ARR_1_1_0_20_fft_counter___d421;
  reg CASE_fft_counter_0_fft_inputFIFOEMPTY_N_AND_f_ETC__q10;
  wire [63 : 0] IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d100,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d143,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d181,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d242,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d294,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d337,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d375,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d439,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d44,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d495,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d538,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d576,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d637,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d689,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d732,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d770,
		x__h293532,
		x__h297016,
		x__h300470,
		x__h303896,
		x__h307845,
		x__h311327,
		x__h314779,
		x__h318203,
		x__h322150,
		x__h325634,
		x__h329088,
		x__h332514,
		x__h48557,
		x__h52353,
		x__h56008,
		x__h59430;
  wire [47 : 0] IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d114,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d157,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d195,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d256,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d308,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d351,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d389,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d453,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d509,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d552,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d58,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d590,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d651,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d703,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d746,
		IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d784,
		x__h293119,
		x__h296603,
		x__h300057,
		x__h303483,
		x__h307432,
		x__h310914,
		x__h314366,
		x__h317790,
		x__h321737,
		x__h325221,
		x__h328675,
		x__h332101,
		x__h48144,
		x__h51940,
		x__h55595,
		x__h59017;
  wire [31 : 0] IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d139,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d20,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d220,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d223,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d23,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d279,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d333,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d415,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d418,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d476,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d534,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d616,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d619,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d674,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d728,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d81,
		SEL_ARR_1_1_0_20_fft_counter_21_CONCAT_SEL_ARR_ETC___d436,
		x__h105335,
		x__h112394,
		x__h19172,
		x__h22791,
		x__h235318,
		x__h235462,
		x__h242385,
		x__h242400,
		x__h249636,
		x__h249780,
		x__h256699,
		x__h256714,
		x__h263946,
		x__h264090,
		x__h271013,
		x__h271028,
		x__h292561,
		x__h297095,
		x__h299628,
		x__h303975,
		x__h306874,
		x__h311404,
		x__h313937,
		x__h318280,
		x__h321179,
		x__h325713,
		x__h328246,
		x__h332593,
		x__h34079,
		x__h37698,
		x__h4258,
		x__h47516,
		x__h47730,
		x__h48985,
		x__h52598,
		x__h55152,
		x__h55181,
		x__h7882;
  wire [15 : 0] IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q1,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q2,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q3,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q4,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q5,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q7,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q8,
		IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q9,
		y_f__h294721,
		y_f__h298147,
		y_f__h301601,
		y_f__h305027,
		y_f__h309032,
		y_f__h312456,
		y_f__h315908,
		y_f__h319332,
		y_f__h323339,
		y_f__h326765,
		y_f__h330219,
		y_f__h333645,
		y_f__h50058,
		y_f__h53671,
		y_f__h57135,
		y_f__h60557;

  // action method request_put
  assign RDY_request_put = fft_inputFIFO$FULL_N ;
  assign CAN_FIRE_request_put = fft_inputFIFO$FULL_N ;
  assign WILL_FIRE_request_put = EN_request_put ;

  // actionvalue method response_get
  assign response_get = fft_outputFIFO$D_OUT ;
  assign RDY_response_get = fft_outputFIFO$EMPTY_N ;
  assign CAN_FIRE_response_get = fft_outputFIFO$EMPTY_N ;
  assign WILL_FIRE_response_get = EN_response_get ;

  // submodule fft_counter_double_write_error
  RevertReg #(.width(32'd1),
	      .init(1'd1)) fft_counter_double_write_error(.CLK(CLK),
							  .D_IN(fft_counter_double_write_error$D_IN),
							  .EN(fft_counter_double_write_error$EN),
							  .Q_OUT(fft_counter_double_write_error$Q_OUT));

  // submodule fft_inputFIFO
  FIFO2 #(.width(32'd512), .guarded(1'd1)) fft_inputFIFO(.RST(RST_N),
							 .CLK(CLK),
							 .D_IN(fft_inputFIFO$D_IN),
							 .ENQ(fft_inputFIFO$ENQ),
							 .DEQ(fft_inputFIFO$DEQ),
							 .CLR(fft_inputFIFO$CLR),
							 .D_OUT(fft_inputFIFO$D_OUT),
							 .FULL_N(fft_inputFIFO$FULL_N),
							 .EMPTY_N(fft_inputFIFO$EMPTY_N));

  // submodule fft_outputFIFO
  FIFO2 #(.width(32'd512), .guarded(1'd1)) fft_outputFIFO(.RST(RST_N),
							  .CLK(CLK),
							  .D_IN(fft_outputFIFO$D_IN),
							  .ENQ(fft_outputFIFO$ENQ),
							  .DEQ(fft_outputFIFO$DEQ),
							  .CLR(fft_outputFIFO$CLR),
							  .D_OUT(fft_outputFIFO$D_OUT),
							  .FULL_N(fft_outputFIFO$FULL_N),
							  .EMPTY_N(fft_outputFIFO$EMPTY_N));

  // submodule fft_sReg_double_write_error
  RevertReg #(.width(32'd1),
	      .init(1'd1)) fft_sReg_double_write_error(.CLK(CLK),
						       .D_IN(fft_sReg_double_write_error$D_IN),
						       .EN(fft_sReg_double_write_error$EN),
						       .Q_OUT(fft_sReg_double_write_error$Q_OUT));

  // rule RL_fft_circ_fft
  assign CAN_FIRE_RL_fft_circ_fft =
	     fft_counter_double_write_error$Q_OUT &&
	     CASE_fft_counter_0_fft_inputFIFOEMPTY_N_AND_f_ETC__q10 ;
  assign WILL_FIRE_RL_fft_circ_fft = CAN_FIRE_RL_fft_circ_fft ;

  // register fft_counter
  assign fft_counter$D_IN =
	     (fft_counter == 2'd2) ? 2'd0 : fft_counter + 2'd1 ;
  assign fft_counter$EN = CAN_FIRE_RL_fft_circ_fft ;

  // register fft_sReg
  assign fft_sReg$D_IN = fft_outputFIFO$D_IN ;
  assign fft_sReg$EN = WILL_FIRE_RL_fft_circ_fft && fft_counter != 2'd2 ;

  // submodule fft_counter_double_write_error
  assign fft_counter_double_write_error$D_IN = 1'd1 ;
  assign fft_counter_double_write_error$EN = CAN_FIRE_RL_fft_circ_fft ;

  // submodule fft_inputFIFO
  assign fft_inputFIFO$D_IN =
	     { request_put[511:448],
	       request_put[255:192],
	       request_put[383:320],
	       request_put[127:64],
	       request_put[447:384],
	       request_put[191:128],
	       request_put[319:256],
	       request_put[63:0] } ;
  assign fft_inputFIFO$ENQ = EN_request_put ;
  assign fft_inputFIFO$DEQ =
	     WILL_FIRE_RL_fft_circ_fft && fft_counter == 2'd0 ;
  assign fft_inputFIFO$CLR = 1'b0 ;

  // submodule fft_outputFIFO
  assign fft_outputFIFO$D_IN =
	     { x__h235318,
	       x__h242385,
	       x__h249636,
	       x__h256699,
	       x__h263946,
	       x__h271013,
	       x__h47516,
	       x__h55152,
	       x__h292561,
	       x__h299628,
	       x__h306874,
	       x__h313937,
	       x__h321179,
	       x__h328246,
	       x__h105335,
	       x__h112394 } ;
  assign fft_outputFIFO$ENQ =
	     WILL_FIRE_RL_fft_circ_fft && fft_counter == 2'd2 ;
  assign fft_outputFIFO$DEQ = EN_response_get ;
  assign fft_outputFIFO$CLR = 1'b0 ;

  // submodule fft_sReg_double_write_error
  assign fft_sReg_double_write_error$D_IN = 1'd1 ;
  assign fft_sReg_double_write_error$EN =
	     WILL_FIRE_RL_fft_circ_fft && fft_counter != 2'd2 ;

  // remaining internal signals
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d100 =
	     x__h7882 * x__h297095 ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d114 =
	     x__h297016[63:16] + { 32'd0, y_f__h298147 } ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d143 =
	     x__h4258 * x__h297095 ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d157 =
	     x__h300470[63:16] + { 32'd0, y_f__h301601 } ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d181 =
	     x__h7882 * x__h303975 ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d195 =
	     x__h303896[63:16] + { 32'd0, y_f__h305027 } ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d242 =
	     x__h19172 * x__h318280 ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d256 =
	     x__h307845[63:16] + { 32'd0, y_f__h309032 } ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d294 =
	     x__h22791 * x__h311404 ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d308 =
	     x__h311327[63:16] + { 32'd0, y_f__h312456 } ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d337 =
	     x__h19172 * x__h311404 ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d351 =
	     x__h314779[63:16] + { 32'd0, y_f__h315908 } ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d375 =
	     x__h22791 * x__h318280 ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d389 =
	     x__h318203[63:16] + { 32'd0, y_f__h319332 } ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d439 =
	     x__h34079 * x__h332593 ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d44 =
	     x__h4258 * x__h303975 ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d453 =
	     x__h322150[63:16] + { 32'd0, y_f__h323339 } ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d495 =
	     x__h37698 * x__h325713 ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d509 =
	     x__h325634[63:16] + { 32'd0, y_f__h326765 } ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d538 =
	     x__h34079 * x__h325713 ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d552 =
	     x__h329088[63:16] + { 32'd0, y_f__h330219 } ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d576 =
	     x__h37698 * x__h332593 ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d58 =
	     x__h293532[63:16] + { 32'd0, y_f__h294721 } ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d590 =
	     x__h332514[63:16] + { 32'd0, y_f__h333645 } ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d637 =
	     x__h48985 * 32'd65536 ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d651 =
	     x__h48557[63:16] + { 32'd0, y_f__h50058 } ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d689 =
	     x__h52598 * 32'd0 ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d703 =
	     x__h52353[63:16] + { 32'd0, y_f__h53671 } ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d732 =
	     x__h48985 * 32'd0 ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d746 =
	     x__h56008[63:16] + { 32'd0, y_f__h57135 } ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d770 =
	     x__h52598 * 32'd65536 ;
  assign IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d784 =
	     x__h59430[63:16] + { 32'd0, y_f__h60557 } ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q1 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[511:496] :
	       fft_sReg[511:496] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q2 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[479:464] :
	       fft_sReg[479:464] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q3 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[383:368] :
	       fft_sReg[383:368] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q4 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[351:336] :
	       fft_sReg[351:336] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q5 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[255:240] :
	       fft_sReg[255:240] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q7 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[223:208] :
	       fft_sReg[223:208] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q8 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[127:112] :
	       fft_sReg[127:112] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q9 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[95:80] :
	       fft_sReg[95:80] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d139 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[415:384] :
	       fft_sReg[415:384] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d20 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[447:416] :
	       fft_sReg[447:416] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d220 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[319:288] :
	       fft_sReg[319:288] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d223 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[383:352] :
	       fft_sReg[383:352] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d23 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[511:480] :
	       fft_sReg[511:480] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d279 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[351:320] :
	       fft_sReg[351:320] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d333 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[287:256] :
	       fft_sReg[287:256] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d415 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[191:160] :
	       fft_sReg[191:160] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d418 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[255:224] :
	       fft_sReg[255:224] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d476 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[223:192] :
	       fft_sReg[223:192] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d534 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[159:128] :
	       fft_sReg[159:128] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d616 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[63:32] :
	       fft_sReg[63:32] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d619 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[127:96] :
	       fft_sReg[127:96] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d674 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[95:64] :
	       fft_sReg[95:64] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d728 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[31:0] :
	       fft_sReg[31:0] ;
  assign IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d81 =
	     (fft_counter == 2'd0) ?
	       fft_inputFIFO$D_OUT[479:448] :
	       fft_sReg[479:448] ;
  assign SEL_ARR_1_1_0_20_fft_counter_21_CONCAT_SEL_ARR_ETC___d436 =
	     { SEL_ARR_1_1_0_20_fft_counter___d421,
	       CASE_fft_counter_0_0_1_0_2_46340_3_DONTCARE_DO_ETC__q6 } ;
  assign x__h105335 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d616 +
	     x__h47730 ;
  assign x__h112394 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d728 +
	     x__h55181 ;
  assign x__h19172 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q3[15] ?
	       -IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d223 :
	       IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d223 ;
  assign x__h22791 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q4[15] ?
	       -IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d279 :
	       IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d279 ;
  assign x__h235318 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d20 -
	     x__h235462 ;
  assign x__h235462 =
	     ((!x__h293119[47] &&
	       (x__h293119[31] || x__h293119[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h293119[47] &&
		  (!x__h293119[31] || ~x__h293119[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h293119[31:0])) -
	     ((!x__h296603[47] &&
	       (x__h296603[31] || x__h296603[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h296603[47] &&
		  (!x__h296603[31] || ~x__h296603[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h296603[31:0])) ;
  assign x__h242385 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d139 -
	     x__h242400 ;
  assign x__h242400 =
	     ((!x__h300057[47] &&
	       (x__h300057[31] || x__h300057[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h300057[47] &&
		  (!x__h300057[31] || ~x__h300057[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h300057[31:0])) +
	     ((!x__h303483[47] &&
	       (x__h303483[31] || x__h303483[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h303483[47] &&
		  (!x__h303483[31] || ~x__h303483[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h303483[31:0])) ;
  assign x__h249636 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d220 -
	     x__h249780 ;
  assign x__h249780 =
	     ((!x__h307432[47] &&
	       (x__h307432[31] || x__h307432[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h307432[47] &&
		  (!x__h307432[31] || ~x__h307432[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h307432[31:0])) -
	     ((!x__h310914[47] &&
	       (x__h310914[31] || x__h310914[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h310914[47] &&
		  (!x__h310914[31] || ~x__h310914[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h310914[31:0])) ;
  assign x__h256699 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d333 -
	     x__h256714 ;
  assign x__h256714 =
	     ((!x__h314366[47] &&
	       (x__h314366[31] || x__h314366[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h314366[47] &&
		  (!x__h314366[31] || ~x__h314366[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h314366[31:0])) +
	     ((!x__h317790[47] &&
	       (x__h317790[31] || x__h317790[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h317790[47] &&
		  (!x__h317790[31] || ~x__h317790[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h317790[31:0])) ;
  assign x__h263946 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d415 -
	     x__h264090 ;
  assign x__h264090 =
	     ((!x__h321737[47] &&
	       (x__h321737[31] || x__h321737[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h321737[47] &&
		  (!x__h321737[31] || ~x__h321737[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h321737[31:0])) -
	     ((!x__h325221[47] &&
	       (x__h325221[31] || x__h325221[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h325221[47] &&
		  (!x__h325221[31] || ~x__h325221[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h325221[31:0])) ;
  assign x__h271013 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d534 -
	     x__h271028 ;
  assign x__h271028 =
	     ((!x__h328675[47] &&
	       (x__h328675[31] || x__h328675[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h328675[47] &&
		  (!x__h328675[31] || ~x__h328675[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h328675[31:0])) +
	     ((!x__h332101[47] &&
	       (x__h332101[31] || x__h332101[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h332101[47] &&
		  (!x__h332101[31] || ~x__h332101[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h332101[31:0])) ;
  assign x__h292561 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d20 +
	     x__h235462 ;
  assign x__h293119 =
	     (!x__h293532[63] &&
	      IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d58[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d58 ;
  assign x__h293532 =
	     (IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d23[31] &&
	      !SEL_ARR_1_0_65535_5_fft_counter___d26[15] ||
	      SEL_ARR_1_0_65535_5_fft_counter___d26[15] &&
	      !IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d23[31]) ?
	       -IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d44 :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d44 ;
  assign x__h296603 =
	     (!x__h297016[63] &&
	      IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d114[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d114 ;
  assign x__h297016 =
	     (IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d81[31] &&
	      !SEL_ARR_0_65535_65535_3_fft_counter___d84[15] ||
	      SEL_ARR_0_65535_65535_3_fft_counter___d84[15] &&
	      !IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d81[31]) ?
	       -IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d100 :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d100 ;
  assign x__h297095 =
	     SEL_ARR_0_65535_65535_3_fft_counter___d84[15] ?
	       -{ SEL_ARR_0_65535_65535_3_fft_counter___d84,
		  SEL_ARR_0_0_19195_9_fft_counter___d40 } :
	       { SEL_ARR_0_65535_65535_3_fft_counter___d84,
		 SEL_ARR_0_0_19195_9_fft_counter___d40 } ;
  assign x__h299628 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d139 +
	     x__h242400 ;
  assign x__h300057 =
	     (!x__h300470[63] &&
	      IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d157[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d157 ;
  assign x__h300470 =
	     (IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d23[31] &&
	      !SEL_ARR_0_65535_65535_3_fft_counter___d84[15] ||
	      SEL_ARR_0_65535_65535_3_fft_counter___d84[15] &&
	      !IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d23[31]) ?
	       -IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d143 :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d143 ;
  assign x__h303483 =
	     (!x__h303896[63] &&
	      IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d195[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d195 ;
  assign x__h303896 =
	     (IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d81[31] &&
	      !SEL_ARR_1_0_65535_5_fft_counter___d26[15] ||
	      SEL_ARR_1_0_65535_5_fft_counter___d26[15] &&
	      !IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d81[31]) ?
	       -IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d181 :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d181 ;
  assign x__h303975 =
	     SEL_ARR_1_0_65535_5_fft_counter___d26[15] ?
	       -{ SEL_ARR_1_0_65535_5_fft_counter___d26,
		  SEL_ARR_0_0_19195_9_fft_counter___d40 } :
	       { SEL_ARR_1_0_65535_5_fft_counter___d26,
		 SEL_ARR_0_0_19195_9_fft_counter___d40 } ;
  assign x__h306874 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d220 +
	     x__h249780 ;
  assign x__h307432 =
	     (!x__h307845[63] &&
	      IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d256[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d256 ;
  assign x__h307845 =
	     (IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d223[31] &&
	      !SEL_ARR_1_0_0_25_fft_counter___d226[15] ||
	      SEL_ARR_1_0_0_25_fft_counter___d226[15] &&
	      !IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d223[31]) ?
	       -IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d242 :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d242 ;
  assign x__h310914 =
	     (!x__h311327[63] &&
	      IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d308[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d308 ;
  assign x__h311327 =
	     (IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d279[31] &&
	      !SEL_ARR_0_65535_65535_3_fft_counter___d84[15] ||
	      SEL_ARR_0_65535_65535_3_fft_counter___d84[15] &&
	      !IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d279[31]) ?
	       -IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d294 :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d294 ;
  assign x__h311404 =
	     SEL_ARR_0_65535_65535_3_fft_counter___d84[15] ?
	       -{ SEL_ARR_0_65535_65535_3_fft_counter___d84, 16'd0 } :
	       { SEL_ARR_0_65535_65535_3_fft_counter___d84, 16'd0 } ;
  assign x__h313937 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d333 +
	     x__h256714 ;
  assign x__h314366 =
	     (!x__h314779[63] &&
	      IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d351[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d351 ;
  assign x__h314779 =
	     (IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d223[31] &&
	      !SEL_ARR_0_65535_65535_3_fft_counter___d84[15] ||
	      SEL_ARR_0_65535_65535_3_fft_counter___d84[15] &&
	      !IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d223[31]) ?
	       -IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d337 :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d337 ;
  assign x__h317790 =
	     (!x__h318203[63] &&
	      IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d389[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d389 ;
  assign x__h318203 =
	     (IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d279[31] &&
	      !SEL_ARR_1_0_0_25_fft_counter___d226[15] ||
	      SEL_ARR_1_0_0_25_fft_counter___d226[15] &&
	      !IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d279[31]) ?
	       -IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d375 :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d375 ;
  assign x__h318280 =
	     SEL_ARR_1_0_0_25_fft_counter___d226[15] ?
	       -{ SEL_ARR_1_0_0_25_fft_counter___d226, 16'd0 } :
	       { SEL_ARR_1_0_0_25_fft_counter___d226, 16'd0 } ;
  assign x__h321179 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d415 +
	     x__h264090 ;
  assign x__h321737 =
	     (!x__h322150[63] &&
	      IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d453[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d453 ;
  assign x__h322150 =
	     (IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d418[31] &&
	      !SEL_ARR_1_1_0_20_fft_counter___d421[15] ||
	      SEL_ARR_1_1_0_20_fft_counter___d421[15] &&
	      !IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d418[31]) ?
	       -IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d439 :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d439 ;
  assign x__h325221 =
	     (!x__h325634[63] &&
	      IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d509[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d509 ;
  assign x__h325634 =
	     (IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d476[31] &&
	      !SEL_ARR_0_0_65535_78_fft_counter___d479[15] ||
	      SEL_ARR_0_0_65535_78_fft_counter___d479[15] &&
	      !IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d476[31]) ?
	       -IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d495 :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d495 ;
  assign x__h325713 =
	     SEL_ARR_0_0_65535_78_fft_counter___d479[15] ?
	       -{ SEL_ARR_0_0_65535_78_fft_counter___d479,
		  SEL_ARR_0_0_19195_9_fft_counter___d40 } :
	       { SEL_ARR_0_0_65535_78_fft_counter___d479,
		 SEL_ARR_0_0_19195_9_fft_counter___d40 } ;
  assign x__h328246 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d534 +
	     x__h271028 ;
  assign x__h328675 =
	     (!x__h329088[63] &&
	      IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d552[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d552 ;
  assign x__h329088 =
	     (IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d418[31] &&
	      !SEL_ARR_0_0_65535_78_fft_counter___d479[15] ||
	      SEL_ARR_0_0_65535_78_fft_counter___d479[15] &&
	      !IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d418[31]) ?
	       -IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d538 :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d538 ;
  assign x__h332101 =
	     (!x__h332514[63] &&
	      IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d590[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d590 ;
  assign x__h332514 =
	     (IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d476[31] &&
	      !SEL_ARR_1_1_0_20_fft_counter___d421[15] ||
	      SEL_ARR_1_1_0_20_fft_counter___d421[15] &&
	      !IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d476[31]) ?
	       -IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d576 :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d576 ;
  assign x__h332593 =
	     SEL_ARR_1_1_0_20_fft_counter___d421[15] ?
	       -SEL_ARR_1_1_0_20_fft_counter_21_CONCAT_SEL_ARR_ETC___d436 :
	       SEL_ARR_1_1_0_20_fft_counter_21_CONCAT_SEL_ARR_ETC___d436 ;
  assign x__h34079 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q5[15] ?
	       -IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d418 :
	       IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d418 ;
  assign x__h37698 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q7[15] ?
	       -IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d476 :
	       IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d476 ;
  assign x__h4258 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q1[15] ?
	       -IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d23 :
	       IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d23 ;
  assign x__h47516 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d616 -
	     x__h47730 ;
  assign x__h47730 =
	     ((!x__h48144[47] &&
	       (x__h48144[31] || x__h48144[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h48144[47] &&
		  (!x__h48144[31] || ~x__h48144[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h48144[31:0])) -
	     ((!x__h51940[47] &&
	       (x__h51940[31] || x__h51940[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h51940[47] &&
		  (!x__h51940[31] || ~x__h51940[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h51940[31:0])) ;
  assign x__h48144 =
	     (!x__h48557[63] &&
	      IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d651[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d651 ;
  assign x__h48557 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d619[31] ?
	       -IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d637 :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d637 ;
  assign x__h48985 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q8[15] ?
	       -IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d619 :
	       IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d619 ;
  assign x__h51940 =
	     (!x__h52353[63] &&
	      IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d703[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d703 ;
  assign x__h52353 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d674[31] ?
	       -IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d689 :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d689 ;
  assign x__h52598 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q9[15] ?
	       -IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d674 :
	       IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d674 ;
  assign x__h55152 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d728 -
	     x__h55181 ;
  assign x__h55181 =
	     ((!x__h55595[47] &&
	       (x__h55595[31] || x__h55595[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h55595[47] &&
		  (!x__h55595[31] || ~x__h55595[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h55595[31:0])) +
	     ((!x__h59017[47] &&
	       (x__h59017[31] || x__h59017[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h59017[47] &&
		  (!x__h59017[31] || ~x__h59017[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h59017[31:0])) ;
  assign x__h55595 =
	     (!x__h56008[63] &&
	      IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d746[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d746 ;
  assign x__h56008 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d619[31] ?
	       -IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d732 :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d732 ;
  assign x__h59017 =
	     (!x__h59430[63] &&
	      IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d784[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d784 ;
  assign x__h59430 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d674[31] ?
	       -IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d770 :
	       IF_IF_fft_counter_EQ_0_THEN_fft_inputFIFO_firs_ETC___d770 ;
  assign x__h7882 =
	     IF_fft_counter_EQ_0_THEN_fft_inputFIFOD_OUT_B_ETC__q2[15] ?
	       -IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d81 :
	       IF_fft_counter_EQ_0_THEN_fft_inputFIFO_first___ETC___d81 ;
  assign y_f__h294721 =
	     (x__h293532[15] &&
	      (x__h293532[63] || x__h293532[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h298147 =
	     (x__h297016[15] &&
	      (x__h297016[63] || x__h297016[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h301601 =
	     (x__h300470[15] &&
	      (x__h300470[63] || x__h300470[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h305027 =
	     (x__h303896[15] &&
	      (x__h303896[63] || x__h303896[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h309032 =
	     (x__h307845[15] &&
	      (x__h307845[63] || x__h307845[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h312456 =
	     (x__h311327[15] &&
	      (x__h311327[63] || x__h311327[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h315908 =
	     (x__h314779[15] &&
	      (x__h314779[63] || x__h314779[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h319332 =
	     (x__h318203[15] &&
	      (x__h318203[63] || x__h318203[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h323339 =
	     (x__h322150[15] &&
	      (x__h322150[63] || x__h322150[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h326765 =
	     (x__h325634[15] &&
	      (x__h325634[63] || x__h325634[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h330219 =
	     (x__h329088[15] &&
	      (x__h329088[63] || x__h329088[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h333645 =
	     (x__h332514[15] &&
	      (x__h332514[63] || x__h332514[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h50058 =
	     (x__h48557[15] && (x__h48557[63] || x__h48557[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h53671 =
	     (x__h52353[15] && (x__h52353[63] || x__h52353[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h57135 =
	     (x__h56008[15] && (x__h56008[63] || x__h56008[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h60557 =
	     (x__h59430[15] && (x__h59430[63] || x__h59430[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  always@(fft_counter)
  begin
    case (fft_counter)
      2'd0: SEL_ARR_1_0_65535_5_fft_counter___d26 = 16'd1;
      2'd1: SEL_ARR_1_0_65535_5_fft_counter___d26 = 16'd0;
      2'd2: SEL_ARR_1_0_65535_5_fft_counter___d26 = 16'd65535;
      2'd3:
	  SEL_ARR_1_0_65535_5_fft_counter___d26 =
	      16'b1010101010101010 /* unspecified value */ ;
    endcase
  end
  always@(fft_counter)
  begin
    case (fft_counter)
      2'd0, 2'd1: SEL_ARR_0_0_19195_9_fft_counter___d40 = 16'd0;
      2'd2: SEL_ARR_0_0_19195_9_fft_counter___d40 = 16'd19195;
      2'd3:
	  SEL_ARR_0_0_19195_9_fft_counter___d40 =
	      16'b1010101010101010 /* unspecified value */ ;
    endcase
  end
  always@(fft_counter)
  begin
    case (fft_counter)
      2'd0: SEL_ARR_0_65535_65535_3_fft_counter___d84 = 16'd0;
      2'd1, 2'd2: SEL_ARR_0_65535_65535_3_fft_counter___d84 = 16'd65535;
      2'd3:
	  SEL_ARR_0_65535_65535_3_fft_counter___d84 =
	      16'b1010101010101010 /* unspecified value */ ;
    endcase
  end
  always@(fft_counter)
  begin
    case (fft_counter)
      2'd0: SEL_ARR_1_0_0_25_fft_counter___d226 = 16'd1;
      2'd1, 2'd2: SEL_ARR_1_0_0_25_fft_counter___d226 = 16'd0;
      2'd3:
	  SEL_ARR_1_0_0_25_fft_counter___d226 =
	      16'b1010101010101010 /* unspecified value */ ;
    endcase
  end
  always@(fft_counter)
  begin
    case (fft_counter)
      2'd0, 2'd1: SEL_ARR_1_1_0_20_fft_counter___d421 = 16'd1;
      2'd2: SEL_ARR_1_1_0_20_fft_counter___d421 = 16'd0;
      2'd3:
	  SEL_ARR_1_1_0_20_fft_counter___d421 =
	      16'b1010101010101010 /* unspecified value */ ;
    endcase
  end
  always@(fft_counter)
  begin
    case (fft_counter)
      2'd0, 2'd1:
	  CASE_fft_counter_0_0_1_0_2_46340_3_DONTCARE_DO_ETC__q6 = 16'd0;
      2'd2:
	  CASE_fft_counter_0_0_1_0_2_46340_3_DONTCARE_DO_ETC__q6 = 16'd46340;
      2'd3:
	  CASE_fft_counter_0_0_1_0_2_46340_3_DONTCARE_DO_ETC__q6 =
	      16'b1010101010101010 /* unspecified value */ ;
    endcase
  end
  always@(fft_counter)
  begin
    case (fft_counter)
      2'd0, 2'd1: SEL_ARR_0_0_65535_78_fft_counter___d479 = 16'd0;
      2'd2: SEL_ARR_0_0_65535_78_fft_counter___d479 = 16'd65535;
      2'd3:
	  SEL_ARR_0_0_65535_78_fft_counter___d479 =
	      16'b1010101010101010 /* unspecified value */ ;
    endcase
  end
  always@(fft_counter or
	  fft_sReg_double_write_error$Q_OUT or
	  fft_inputFIFO$EMPTY_N or fft_outputFIFO$FULL_N)
  begin
    case (fft_counter)
      2'd0:
	  CASE_fft_counter_0_fft_inputFIFOEMPTY_N_AND_f_ETC__q10 =
	      fft_inputFIFO$EMPTY_N && fft_sReg_double_write_error$Q_OUT;
      2'd2:
	  CASE_fft_counter_0_fft_inputFIFOEMPTY_N_AND_f_ETC__q10 =
	      fft_outputFIFO$FULL_N;
      default: CASE_fft_counter_0_fft_inputFIFOEMPTY_N_AND_f_ETC__q10 =
		   fft_sReg_double_write_error$Q_OUT;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        fft_counter <= `BSV_ASSIGNMENT_DELAY 2'd0;
      end
    else
      begin
        if (fft_counter$EN)
	  fft_counter <= `BSV_ASSIGNMENT_DELAY fft_counter$D_IN;
      end
    if (fft_sReg$EN) fft_sReg <= `BSV_ASSIGNMENT_DELAY fft_sReg$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    fft_counter = 2'h2;
    fft_sReg =
	512'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkFFT

